name = "tempo-pdf-worker"
compatibility_date = "2024-05-10"

# R2 Bucket Konfiguration
[[r2_buckets]]
binding = "R2_BUCKET_BINDING"         # Name für den Zugriff im Code über env.R2_BUCKET_BINDING
bucket_name = "books"    # Produktions-Bucket Name
preview_bucket_name = "books" # Preview-Bucket für wrangler dev --remote
